baseURL = "http://bryanbugyi.com/"
languageCode = "en-us"
title = "A Tech Blog by Bryan Bugyi"
newContentEditor = "vim"
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
tags = ["portfolio", "web design", "blog"]
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-129349538-1"
disqusShortname = "bryanbugyi"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = """"There is nothing more unproductive than to build something efficiently that should not have been built at all." - Milt Bryce"""
    author = "Bryan Bugyi"
    description = "Software Engineer in training. Currently studying Computer Science and Mathematics at Rutgers University. I am on track to graduate in the Spring of 2018."
    logoBig = "/images/BB-256.svg"
    logoSmall = "/images/BB-64.svg"
    favicon = "favicon.ico"
    opengraphImage = "/images/BB-128.svg"
    twitter = "bryan_bugyi"
    linkedin = "bryan-bugyi-a3650763"
    github = "bbugyi200"
    facebook = ""
    email = "bryanbugyi34@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 3
