baseURL = "http://bryanbugyi.com/"
canonifyURLS = true
categories = ["vim", "commandline", "gentoo"]
config = "config.toml"
disqusShortname = "bryanbugyi"
enableEmoji = true
googleAnalytics = "UA-129349538-1"
languageCode = "en-us"
newContentEditor = "vim"
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
theme = "osprey"
title = "A Tech Blog by Bryan Bugyi"

[Params]
    ajaxFormspree = true
    author = "Bryan Bugyi"
    cacheBustCSS = false
    cacheBustJS = false
    copyright = false
    credit = false
    customCSS = true
    description = "A blog focused on providing technical tips and tutorials on all things related to automation. In particular, the vim editor and the Unix commandline are covered often."
    email = "bryanbugyi34@gmail.com"
    facebook = ""
    favicon = "favicon.ico"
    github = "bbugyi200"
    googleTagManager = ""
    highlightJS = true
    linkedin = "bryan-bugyi-a3650763"
    logoBig = "/images/BB-256.svg"
    logoSmall = "/images/BB-64.svg"
    opengraphImage = "/images/BB-128.svg"
    tagline = """"Good design adds value faster than it adds cost." - Thomas C. Gale"""
    twitter = "bryan_bugyi"

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 3
